"""Reports reading UX: build an index, a stable 'latest' pointer, and inter-day navigation.

The digests in reports/ are flat dated files (reports/YYYY-MM-DD-digest.md). With many of them,
finding and moving between days is clumsy. This regenerates three reading aids each run (cheap,
deterministic, stdlib only) so they never drift from the actual files:

  reports/README.md   newest-first index table (date · top-line · link). GitHub renders it as
                      the folder landing page, so opening reports/ *is* the reading list.
  reports/latest.md   a copy of the most recent digest -> one fixed path to "read the latest".
  per-digest nav      an idempotent  `← prev · index · next →`  header injected at the top of
                      each digest, so you can walk days without leaving the file.

Idempotent by design: the nav block is delimited by HTML comment markers and fully rewritten
each run, so re-running never stacks duplicate nav lines. Safe to run after every distill.

Run: python -m distill.reindex
"""
from __future__ import annotations
import re, sys, shutil
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from collectors.common import ROOT  # noqa: E402

REPORTS = ROOT / "reports"
NAV_START = "<!-- radar:nav -->"
NAV_END = "<!-- /radar:nav -->"
DATE_RE = re.compile(r"(\d{4}-\d{2}-\d{2})-digest\.md$")
NAV_BLOCK_RE = re.compile(
    re.escape(NAV_START) + r".*?" + re.escape(NAV_END) + r"\n?", re.DOTALL)


def digest_files() -> list[Path]:
    """All dated digests, OLDEST first. Excludes generated files (README/latest)."""
    files = [p for p in REPORTS.glob("*.md")
             if DATE_RE.search(p.name) and p.name not in ("README.md", "latest.md")]
    return sorted(files, key=lambda p: DATE_RE.search(p.name).group(1))


def _strip_nav(text: str) -> str:
    """Remove any existing nav block so we can re-inject a fresh one (idempotency)."""
    return NAV_BLOCK_RE.sub("", text, count=1).lstrip("\n")


def _date_of(p: Path) -> str:
    m = DATE_RE.search(p.name)
    return m.group(1) if m else p.stem


def title_of(p: Path) -> str:
    """First H1 (`# ...`) of a digest, nav stripped. Falls back to the date."""
    body = _strip_nav(p.read_text())
    m = re.search(r"^#\s+(.*)$", body, re.MULTILINE)
    return m.group(1).strip() if m else _date_of(p)


def topline_of(p: Path) -> str:
    """First non-empty paragraph after the H1 (the digest's top-line), as a one-line teaser."""
    body = _strip_nav(p.read_text())
    # Drop the H1, then take the first real paragraph that isn't a heading/rule.
    after = re.sub(r"^#\s+.*$", "", body, count=1, flags=re.MULTILINE).strip()
    for para in re.split(r"\n\s*\n", after):
        line = para.strip()
        if line and not line.startswith(("#", "---", "<!--")):
            one = " ".join(line.split())
            return (one[:160] + "…") if len(one) > 160 else one
    return ""


def _nav(prev: Path | None, cur: Path, nxt: Path | None) -> str:
    """Nav line relative to reports/. prev = older day, next = newer day."""
    parts = []
    parts.append(f"[← {_date_of(prev)}]({prev.name})" if prev else "← _oldest_")
    parts.append("[index](README.md)")
    parts.append(f"[{_date_of(nxt)} →]({nxt.name})" if nxt else "_newest_ →")
    return f"{NAV_START}\n`radar`  ·  " + "  ·  ".join(parts) + f"\n{NAV_END}\n\n"


def write_nav(files: list[Path]) -> None:
    """Inject/refresh the prev/index/next nav at the top of each digest (oldest->newest order)."""
    for i, cur in enumerate(files):
        prev = files[i - 1] if i > 0 else None              # older
        nxt = files[i + 1] if i < len(files) - 1 else None  # newer
        body = _strip_nav(cur.read_text())
        cur.write_text(_nav(prev, cur, nxt) + body)


def write_index(files: list[Path]) -> None:
    """Newest-first index table at reports/README.md."""
    rows = []
    for p in reversed(files):                                # newest first
        title = title_of(p)
        # The H1 is usually 'AI Radar — DATE'; show the date column + a trimmed title teaser.
        teaser = topline_of(p)
        rows.append(f"| [{_date_of(p)}]({p.name}) | {teaser} |")
    header = (
        "# AI Radar — report index\n\n"
        "Auto-generated by `distill/reindex.py` after each run. Newest first. "
        "The most recent digest is also always at [latest.md](latest.md).\n\n"
        "| Date | Top-line |\n|------|----------|\n"
    )
    (REPORTS / "README.md").write_text(header + "\n".join(rows) + "\n")


def write_latest(files: list[Path]) -> None:
    """Stable pointer to the newest digest (a copy, so links/render work on any GitHub view)."""
    if not files:
        return
    newest = files[-1]
    body = newest.read_text()  # includes its fresh nav
    (REPORTS / "latest.md").write_text(body)


def main() -> None:
    REPORTS.mkdir(parents=True, exist_ok=True)
    files = digest_files()
    if not files:
        print("[reindex] no digests found; nothing to do.")
        return
    write_nav(files)        # nav first, so index/latest capture the navigated copies
    write_index(files)
    write_latest(files)
    print(f"[reindex] indexed {len(files)} reports; wrote README.md, latest.md, and nav.")


if __name__ == "__main__":
    main()
